// monolito-vue/src/App.vue
<script setup>
import Sidebar from "./components/Sidebar.vue"
import "./index.css"
import Article from "./components/Article.vue"
import Footer from "./components/Footer.vue"

</script>

<template>
  <Sidebar></Sidebar>
  <main>
    <div class="body">
      <Article></Article>
    </div>
  </main>
  <div class="footer">
    <Footer :select="selectArticle"></Footer>
  </div>
</template>

<style scoped>
</style>

// microfront-react/page/src/App.js
import React from 'react';
import Parcel from 'single-spa-react/parcel';
import "./index.css";
export default function App() {
    return (
        <>
            <main>
                <Parcel config={() => System.import('@Giovane/sidebar')}></Parcel>
                <div className='body'>
                    <Parcel config={() => System.import('@Giovane/article')}></Parcel>
                </div>
            </main>
            <footer className='footer'>
                 <Parcel config={() => System.import('@Giovane/footer')}></Parcel>
            </footer>
        </>
    )
}
